export const API_URLS = {


  admin_login: `/api/v1/auth-admin-login`,
  dashboard_api: `/api/v1/admin-dashboard`,


  level_bonus_data: `/api/v1/get-roi-income-details-admin`,
  inr_payout_data: `/api/v1/get-withdrawal-details-admin`,
  topup_data: `/api/v1/get-topup-details-admin`,
  user_data: `/api/v1/get-user-details-admin`,


  withdrawl_Request: `/api/v1/inr-payout-request-list`,
  withdrawl_approved: `/api/v1/inr-payout-request-approval`,
  withdrawl_reject: `/api/v1/inr-payout-request-rejection`,
  withdrawl_approved_list: `/api/v1/inr-payout-request-list-success`,
  withdrawl_reject_list: `/api/v1/inr-payout-request-list-failed`,
  withdrawl_pending_list: `/api/v1/inr-payout-request-list-pending-from-gateway`,
  user_list: `/api/v1/user-list`,
  token_zp: `/api/v1/zp-token-payin-admin`,
  token_zp_payout: `/api/v1/zp-token-payout-admin`,
  inr_payingdata: `/api/v1/gt-inr-fund-request-list`,
  inr_payoutdata: `/api/v1/gt-inr-payout-request-list`,
  inr_manually: `/api/v1/get-withdrawal-list-more-than-ten-hund`,
  inr_manually_Approve: `/api/v1/approve-withdrawal-more-than-ten-hund`,
  get_bonus_list: `/api/v1/get-bonus-list-admin`,
  update_bonus_list: `/api/v1/update-bonus-list-admin`,
  update_user_name: `/api/v1/update-user-name`,
  update_user_status: `/api/v1/update-user-status`,
  wingo_result_api: `/api/v1/update-wingo-result`,
  add_fund: `/api/v1/add-fund-to-user`,
  debit_fund: `/api/v1/fund-debited-by-admin`,
  update_bank: `/api/v1/update-bank-details-by-admin`,
  get_bank_data: `/api/v1/get-bank-details-by-admin`,
  get_fund_history: `/api/v1/fund-transfer-history`,
  debit_fund_history: `/api/v1/fund-debited-by-admin-history`,
  p2p_history: `/api/v1/p-2-p-list-admin`,
  get_aviator_report: `/api/v1/get-aviator-report`,
  get_trx_report: `/api/v1/get-trx-report`,
  get_wingo_report: `/api/v1/get-wingo-report`,
  user_permission: `/api/v1/change-user-permisson`,
  day_book_report: `/api/v1/day-book-report`,
  get_name_code: `/api/v1/get-sponsor-name`,
  Change_Password: `api/v1/change-user-password`,
  up_team: `api/v1/get-up-team`,
  down_team: `api/v1/get-downline-team`,
  welcome_bonus: `/api/v1/tget-wlcm-bonus-admin-data`,
  deposit_bonus_data: `/api/v1/tget-dpst-bonus-admin-data`,
  self_deposit_bonus_data: `/api/v1/tget-dpst-bonus-admin-data`,
  team_referal_bonus_data: `/api/v1/getTeamReferralFirstListAdmin`,
  roi_bonus_data: `/api/v1/tget-roi-bonus-admin-data`,
  daily_salary_bonus_data: `/api/v1/tget-daily-salary-bonus-admin-data`,
  gift_bonus_data: `/api/v1/gift-bonus-list-admin`,
  salary_bonus_data: `/api/v1/tget-daily-salary-bonus-admin-data`,
  weekly_bonus_data: `/api/v1/tget-weekly-recovery-admin-data`,
  welcome_bonus_data: `/api/v1/tget-wlcm-bonus-admin-data`,
  bet_bonus_data: `/api/v1/tget-bet-income-bonus-admin-data`,
 
  vip_bonus_data: `/api/v1/vip-bonus-list-admin`,
  cashback_bonus_data: `/api/v1/cash-back-bonus-list-admin`,
  add_coupon_user: `/api/v1/add-coupon-to-user-by-admin`,
  add_comapany_promoter: `/api/v1/makeCompanyPromotorbyAdmin`,
  comapany_promoter_list: `/api/v1/company-promoter-bonus-list-admin-active`,
  update_company_record: `/api/v1/changePromotorStatus?u_id=`,
  business_chart: `/api/v1/user-business-status-bar-chart`,
  registration_chart: `/api/v1/user-registration-status-bar-chart`,
  trx_chart: `/api/v1/user-trx-status-area-chart`,
  wingo_chart: `/api/v1/user-wingo-status-area-chart`,
  avaitor_chart: `/api/v1/user-aviator-status-area-chart`,
  bonus_set: `/api/v1/set-income-amount`,
  zp_Amount: `/api/v1/set-zp-amount`,
  private_key_data: `/api/v1/aasdfjasfasjfhkjahfkjhaskdaf-ajdfhafjkljhf-ajsfhkahkljdasfhkl`,
  coupon: `/api/v1/get-admin-coupon-list`,
  add_coupon: `/api/v1/add-admin-coupon-list`,
  update_coupon_record: `/api/v1/update-admin-coupon-list?t_id=`,
  set_game_status: `api/v1/set-game-status`,
  set_popup_status: `api/v1/update-popup-status`,
  set_upload: `api/v1/add-popup-image`,
  refresh_status: `api/v1/approve-all-users`,
  rollet_result: `api/v1/update-roulette-result`,
  satka_matka_result: `api/v1/update-satta-matka-result`,
  comapany_promoter: `/api/v1/company-promoter-bonus-list-admin`,
  approval_payin: `/api/v1/manual-approval-payin-by-admin`,

  //close
  get_next_gameid_one_min: `/api/v1/get-bet-one-min-next-id`,
  get_all_player: `/api/v1/getAllPlayer`,
  player_registration: `/api/v1/addPlayer`,
  get_username_by_referralid: `/api/v1/getUsernameBy_refId`,
  get_user_data_by_user_id: `/api/v1/getPlayerDataById`,
  update_player_record: `/api/v1/updatePlayerRecord`,
  winzo_withdrawl: `/api/v1/view-winzo-withdrawl-request-report`,
  wingo_deposit: `/api/v1/view-wingo-main-wallet`,
  add_sub_admin: `/api/v1/addSubAdmin`,
  get_sub_admin_list: `/api/v1/getSubAdmin`,
  get_new_assigned_menu_list: `/api/v1/getAssignSubMenu`,
  get_downline_data_by_id: `/api/v1/downline-referral-data`,
  manually_winning_api: `/api/v1/manually-winning`,
  manually_update_percentage_api: `/api/v1/manually-update-percentage`,
};
